### ISSUE TITLE
[question] how to change icon theme

### ISSUE THREAD

**Issue by gmankab** [wayblueorg/wayblue#45]
hello

there is default icon theme on wayblue:

```shell
cat /usr/share/icons/default/index.theme
[Icon Theme]
Inherits=ePapirus
```

how i can change it to adwaita? i tried to install gnonme-twaks and choose adwaita, but after relogin it was replaced by ePapirus

**Comment by RoyalOughtness** [comment]
It should be possible via `gsettings set org.gnome.desktop.interface icon-theme`, does this not work?

**Comment by gmankab** [comment]
> It should be possible via `gsettings set org.gnome.desktop.interface icon-theme`, does this not work?

works until relogin

after relogin sets to ePapirus

**Comment by RoyalOughtness** [comment]
@gmankab Go to `/etc/profile.d/settheming.sh` and replace 'ePapirus'

**Comment by gmankab** [comment]
> @gmankab Go to `/etc/profile.d/settheming.sh` and replace 'ePapirus'

thank you, it helped

**Comment by fiftydinar** [comment]
To fix this issue without requiring the user to edit `/etc/profile.d/settheming.sh`, wayblue should utilize [`gschema-overrides` BlueBuild module](https://blue-build.org/reference/modules/gschema-overrides/), which will properly set gsettings defaults, while allowing users to normally override & reset settings to default.

So I would like this to be reopened, until this issue is solved.

I can make a PR for this later & test.
