### ISSUE TITLE
[request] replace rpm firefox with flathub firefox by default

### ISSUE THREAD

**Issue by gmankab** [wayblueorg/wayblue#47]
### request

wayblue now offeres rpm firefox by default

can you please replace it with firefox from flathub

### why

- rpm firefox don't have all codecs, while flatpak has all codecs built in 
- rpm firefox creates trash in ~/.mozilla dir, while flatpak only uses ~/.var

**Comment by RoyalOughtness** [comment]
> wayblue now offeres rpm firefox by default

This is not new. It has been like this since day one. Did this change recently for you?

> can you please replace it with firefox from flathub

Preinstalling flatpaks only works with an ISO (which we don't ship) or using a hack (systemd service that installs them on boot, which isn't desirable)

> rpm firefox don't have all codecs, while flatpak has all codecs built in

This shouldn't be the case, it should use the system ffmpeg. I will double check this.



There shouldn't be anything preventing you from doing this locally. Just `rpm-ostree uninstall firefox` and then `flatpak install firefox` from flathub

**Comment by gmankab** [comment]
sorry for being unclear, yes, this was from day one and not change recently

you argued well that rpm firefox may stay, so feel free to close issue
