### ISSUE TITLE
Hyprland image missing lxpolkit in layered applications

### ISSUE THREAD

**Issue by Eoin-ONeill-Yokai** [wayblueorg/wayblue#51]
Despite the configuration having lxpolkit referenced, it was missing from my application list and I had to layer it manually. 

This seems like a bug and it should be included in the `hyprland-basics.yaml` recipe.

**Comment by RoyalOughtness** [comment]
> having lxpolkit referenced,

It doesn't anymore. It was replaced with xfce-polkit. You probably have an old version that's not getting updated because it's overriden

> I had to layer it manually.

xfce-polkit is included and it's working well. you likely have a config override. Run `ujust check-local-overrides` or diff your ~/.config hyprland conf with the one in /usr

**Comment by RoyalOughtness** [comment]
https://github.com/wayblueorg/wayblue/blob/live/config/files/hyprland/usr/share/hyprland/hyprland.conf#L183

**Comment by Eoin-ONeill-Yokai** [comment]
Got it, ok I think I was confused by that. I'll update my configuration.
